### ISSUE TITLE
Ads are back again.

### ISSUE THREAD

**Issue by sunnywu484** [wanam/YouTubeAdAway#7] opened 2017-04-28 07:16 UTC
Seems like ads are back again. YouTube just auto updated and I went latest on the Xposed module.

04-27 20:18:10.298 I/Xposed  ( 4178): -----------------
04-27 20:18:10.298 I/Xposed  ( 4178): Starting Xposed version 84, compiled for SDK 23
04-27 20:18:10.298 I/Xposed  ( 4178): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)
04-27 20:18:10.298 I/Xposed  ( 4178): ROM: MTC19T
04-27 20:18:10.298 I/Xposed  ( 4178): Build fingerprint: google/angler/angler:6.0.1/MTC19T/2741993:user/release-keys
04-27 20:18:10.298 I/Xposed  ( 4178): Platform: arm64-v8a, 64-bit binary, system server: yes
04-27 20:18:10.298 I/Xposed  ( 4178): SELinux enabled: yes, enforcing: yes
04-27 20:18:11.307 I/Xposed  ( 4178): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-27 20:18:11.625 I/Xposed  ( 4178): Detected ART runtime
04-27 20:18:11.656 I/Xposed  ( 4178): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
04-27 20:18:11.892 I/Xposed  ( 4178): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-27 20:18:12.059 I/Xposed  ( 4178):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-27 20:18:12.082 I/Xposed  ( 4178):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-27 20:18:12.083 I/Xposed  ( 4178): Loading modules from /data/app/org.baole.app.blacklist-1/base.apk
04-27 20:18:12.254 I/Xposed  ( 4178):   Loading class com.anttek.blacklist.xposed.PermissionMod
04-27 20:18:12.255 E/Xposed  ( 4178): java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/data/app/org.baole.app.blacklist-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-27 20:18:12.255 E/Xposed  ( 4178): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-27 20:18:12.255 E/Xposed  ( 4178): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-27 20:18:12.255 E/Xposed  ( 4178): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-27 20:18:12.255 E/Xposed  ( 4178): 	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:497)
04-27 20:18:12.255 E/Xposed  ( 4178): 	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:457)
04-27 20:18:12.255 E/Xposed  ( 4178): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:122)
04-27 20:18:12.255 E/Xposed  ( 4178): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-27 20:18:12.255 E/Xposed  ( 4178): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-27 20:18:12.255 E/Xposed  ( 4178): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-27 20:18:12.255 E/Xposed  ( 4178): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-27 20:18:12.255 E/Xposed  ( 4178): 		... 4 more
04-27 20:18:12.255 E/Xposed  ( 4178): 		Suppressed: java.lang.ClassNotFoundException: com.anttek.blacklist.xposed.PermissionMod
04-27 20:18:12.255 E/Xposed  ( 4178): 			at java.lang.Class.classForName(Native Method)
04-27 20:18:12.255 E/Xposed  ( 4178): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-27 20:18:12.255 E/Xposed  ( 4178): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-27 20:18:12.255 E/Xposed  ( 4178): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-27 20:18:12.255 E/Xposed  ( 4178): 			... 5 more
04-27 20:18:12.255 E/Xposed  ( 4178): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-27 20:18:12.256 I/Xposed  ( 4178): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
04-27 20:18:12.256 I/Xposed  ( 4178):   File does not exist
04-27 20:18:20.353 I/Xposed  ( 4182): -----------------
04-27 20:18:20.353 I/Xposed  ( 4182): Starting Xposed version 84, compiled for SDK 23
04-27 20:18:20.353 I/Xposed  ( 4182): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)
04-27 20:18:20.353 I/Xposed  ( 4182): ROM: MTC19T
04-27 20:18:20.353 I/Xposed  ( 4182): Build fingerprint: google/angler/angler:6.0.1/MTC19T/2741993:user/release-keys
04-27 20:18:20.353 I/Xposed  ( 4182): Platform: arm64-v8a, 32-bit binary, system server: no
04-27 20:18:20.353 I/Xposed  ( 4182): SELinux enabled: yes, enforcing: yes
04-27 20:18:20.359 I/Xposed  ( 4182): -----------------
04-27 20:18:20.359 I/Xposed  ( 4182): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-27 20:18:20.761 I/Xposed  ( 4182): Detected ART runtime
04-27 20:18:20.785 I/Xposed  ( 4182): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
04-27 20:18:21.037 I/Xposed  ( 4182): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-27 20:18:21.210 I/Xposed  ( 4182):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-27 20:18:21.233 I/Xposed  ( 4182):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-27 20:18:21.233 I/Xposed  ( 4182): Loading modules from /data/app/org.baole.app.blacklist-1/base.apk
04-27 20:18:21.406 I/Xposed  ( 4182):   Loading class com.anttek.blacklist.xposed.PermissionMod
04-27 20:18:21.407 E/Xposed  ( 4182): java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/data/app/org.baole.app.blacklist-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-27 20:18:21.407 E/Xposed  ( 4182): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-27 20:18:21.407 E/Xposed  ( 4182): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-27 20:18:21.407 E/Xposed  ( 4182): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-27 20:18:21.407 E/Xposed  ( 4182): 	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:497)
04-27 20:18:21.407 E/Xposed  ( 4182): 	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:457)
04-27 20:18:21.407 E/Xposed  ( 4182): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:122)
04-27 20:18:21.407 E/Xposed  ( 4182): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-27 20:18:21.407 E/Xposed  ( 4182): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-27 20:18:21.407 E/Xposed  ( 4182): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-27 20:18:21.407 E/Xposed  ( 4182): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-27 20:18:21.407 E/Xposed  ( 4182): 		... 4 more
04-27 20:18:21.407 E/Xposed  ( 4182): 		Suppressed: java.lang.ClassNotFoundException: com.anttek.blacklist.xposed.PermissionMod
04-27 20:18:21.407 E/Xposed  ( 4182): 			at java.lang.Class.classForName(Native Method)
04-27 20:18:21.407 E/Xposed  ( 4182): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-27 20:18:21.407 E/Xposed  ( 4182): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-27 20:18:21.407 E/Xposed  ( 4182): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-27 20:18:21.407 E/Xposed  ( 4182): 			... 5 more
04-27 20:18:21.407 E/Xposed  ( 4182): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-27 20:18:21.407 I/Xposed  ( 4182): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
04-27 20:18:21.407 I/Xposed  ( 4182):   File does not exist

**Comment by sunnywu484** [comment] 2017-04-28 07:32
The module is checked in Xposed and I've rebooted a couple times but when I open the app in Xposed, it says not active.

04-28 00:27:34.858 I/Xposed  ( 4200): -----------------
04-28 00:27:34.858 I/Xposed  ( 4200): Starting Xposed version 84, compiled for SDK 23
04-28 00:27:34.858 I/Xposed  ( 4200): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)
04-28 00:27:34.858 I/Xposed  ( 4200): ROM: MTC19T
04-28 00:27:34.858 I/Xposed  ( 4200): Build fingerprint: google/angler/angler:6.0.1/MTC19T/2741993:user/release-keys
04-28 00:27:34.858 I/Xposed  ( 4200): Platform: arm64-v8a, 64-bit binary, system server: yes
04-28 00:27:34.858 I/Xposed  ( 4200): SELinux enabled: yes, enforcing: yes
04-28 00:27:35.868 I/Xposed  ( 4200): -----------------
04-28 00:27:35.869 I/Xposed  ( 4200): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-28 00:27:36.223 I/Xposed  ( 4200): Detected ART runtime
04-28 00:27:36.255 I/Xposed  ( 4200): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
04-28 00:27:36.503 I/Xposed  ( 4200): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-28 00:27:36.669 I/Xposed  ( 4200):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-28 00:27:36.693 I/Xposed  ( 4200):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-28 00:27:36.694 I/Xposed  ( 4200): Loading modules from /data/app/org.baole.app.blacklist-1/base.apk
04-28 00:27:36.864 I/Xposed  ( 4200):   Loading class com.anttek.blacklist.xposed.PermissionMod
04-28 00:27:36.865 E/Xposed  ( 4200): java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/data/app/org.baole.app.blacklist-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-28 00:27:36.865 E/Xposed  ( 4200): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 00:27:36.865 E/Xposed  ( 4200): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 00:27:36.865 E/Xposed  ( 4200): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-28 00:27:36.865 E/Xposed  ( 4200): 	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:497)
04-28 00:27:36.865 E/Xposed  ( 4200): 	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:457)
04-28 00:27:36.865 E/Xposed  ( 4200): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:122)
04-28 00:27:36.865 E/Xposed  ( 4200): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
04-28 00:27:36.865 E/Xposed  ( 4200): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 00:27:36.865 E/Xposed  ( 4200): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 00:27:36.865 E/Xposed  ( 4200): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 00:27:36.865 E/Xposed  ( 4200): 		... 4 more
04-28 00:27:36.865 E/Xposed  ( 4200): 		Suppressed: java.lang.ClassNotFoundException: com.anttek.blacklist.xposed.PermissionMod
04-28 00:27:36.865 E/Xposed  ( 4200): 			at java.lang.Class.classForName(Native Method)
04-28 00:27:36.865 E/Xposed  ( 4200): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-28 00:27:36.865 E/Xposed  ( 4200): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-28 00:27:36.865 E/Xposed  ( 4200): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 00:27:36.865 E/Xposed  ( 4200): 			... 5 more
04-28 00:27:36.865 E/Xposed  ( 4200): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-28 00:27:36.865 I/Xposed  ( 4200): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
04-28 00:27:36.866 I/Xposed  ( 4200):   File does not exist
04-28 00:27:45.042 I/Xposed  ( 4201): -----------------
04-28 00:27:45.042 I/Xposed  ( 4201): Starting Xposed version 84, compiled for SDK 23
04-28 00:27:45.042 I/Xposed  ( 4201): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)
04-28 00:27:45.042 I/Xposed  ( 4201): ROM: MTC19T
04-28 00:27:45.042 I/Xposed  ( 4201): Build fingerprint: google/angler/angler:6.0.1/MTC19T/2741993:user/release-keys
04-28 00:27:45.042 I/Xposed  ( 4201): Platform: arm64-v8a, 32-bit binary, system server: no
04-28 00:27:45.042 I/Xposed  ( 4201): SELinux enabled: yes, enforcing: yes
04-28 00:27:45.046 I/Xposed  ( 4201): -----------------
04-28 00:27:45.047 I/Xposed  ( 4201): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-28 00:27:45.439 I/Xposed  ( 4201): Detected ART runtime
04-28 00:27:45.467 I/Xposed  ( 4201): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
04-28 00:27:45.697 I/Xposed  ( 4201): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
04-28 00:27:45.896 I/Xposed  ( 4201):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
04-28 00:27:45.916 I/Xposed  ( 4201):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
04-28 00:27:45.917 I/Xposed  ( 4201): Loading modules from /data/app/org.baole.app.blacklist-1/base.apk
04-28 00:27:46.131 I/Xposed  ( 4201):   Loading class com.anttek.blacklist.xposed.PermissionMod
04-28 00:27:46.132 E/Xposed  ( 4201): java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/data/app/org.baole.app.blacklist-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-28 00:27:46.132 E/Xposed  ( 4201): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 00:27:46.132 E/Xposed  ( 4201): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 00:27:46.132 E/Xposed  ( 4201): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-28 00:27:46.132 E/Xposed  ( 4201): 	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:497)
04-28 00:27:46.132 E/Xposed  ( 4201): 	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:457)
04-28 00:27:46.132 E/Xposed  ( 4201): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:122)
04-28 00:27:46.132 E/Xposed  ( 4201): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.anttek.blacklist.xposed.PermissionMod" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-28 00:27:46.132 E/Xposed  ( 4201): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 00:27:46.132 E/Xposed  ( 4201): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 00:27:46.132 E/Xposed  ( 4201): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 00:27:46.132 E/Xposed  ( 4201): 		... 4 more
04-28 00:27:46.132 E/Xposed  ( 4201): 		Suppressed: java.lang.ClassNotFoundException: com.anttek.blacklist.xposed.PermissionMod
04-28 00:27:46.132 E/Xposed  ( 4201): 			at java.lang.Class.classForName(Native Method)
04-28 00:27:46.132 E/Xposed  ( 4201): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-28 00:27:46.132 E/Xposed  ( 4201): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-28 00:27:46.132 E/Xposed  ( 4201): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 00:27:46.132 E/Xposed  ( 4201): 			... 5 more
04-28 00:27:46.132 E/Xposed  ( 4201): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
04-28 00:27:46.132 I/Xposed  ( 4201): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
04-28 00:27:46.133 I/Xposed  ( 4201):   File does not exist

**Comment by wanam** [comment] 2017-04-28 07:43
Duplicate of https://github.com/wanam/YouTubeAdAway/issues/1
By the way you logs are incomplete, there is no mention of the module.

**Closed by wanam** 2017-04-28 07:43 UTC
