### ISSUE TITLE
Problems with instalation and use

### ISSUE THREAD

**Issue by rash230691** [wanam/YouTubeAdAway#22] opened 2017-07-29 07:56 UTC
After installing the module, when you try to open its application crashes. When using YT in the logs the following:
07-29 10:51:39.930 I/Xposed  (14561): YouTube: com.google.android.youtube 12.23.60 loaded!
07-29 10:51:39.930 I/Xposed  (14561): YouTube AdAway 3.5.3: Trying brute force way...
07-29 10:51:40.792 I/Xposed  (14561): YouTube AdAway: Successfully hooked ads DB: urr
07-29 10:51:41.333 I/Xposed  (14561): YouTube AdAway: Successfully hooked qgy constructor!
07-29 10:51:41.335 I/Xposed  (14561): YouTube AdAway: Successfully hooked qgy param=oxi
07-29 10:51:41.483 E/Xposed  (14561): de.robv.android.xposed.XposedHelpers$InvocationTargetError: android.database.sqlite.SQLiteException: no such table: ads (code 1): , while compiling: ALTER TABLE ads ADD COLUMN ad_intro_video_id TEXT
07-29 10:51:41.483 E/Xposed  (14561): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1225)
07-29 10:51:41.483 E/Xposed  (14561): 	at ma.wanam.youtubeadaway.XYoutube$BFAsync$1.afterHookedMethod(XYoutube.java:119)
07-29 10:51:41.483 E/Xposed  (14561): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-29 10:51:41.483 E/Xposed  (14561): 	at urr.<init>(Unknown Source)
07-29 10:51:41.483 E/Xposed  (14561): 	at uru.get(SourceFile:5)
07-29 10:51:41.483 E/Xposed  (14561): 	at aeab.get(SourceFile:10)
07-29 10:51:41.483 E/Xposed  (14561): 	at usn.get(SourceFile:24)
07-29 10:51:41.483 E/Xposed  (14561): 	at aeab.get(SourceFile:10)
07-29 10:51:41.483 E/Xposed  (14561): 	at upc.a(SourceFile:57)
07-29 10:51:41.483 E/Xposed  (14561): 	at buw.a(SourceFile:299)
07-29 10:51:41.483 E/Xposed  (14561): 	at uob.<init>(SourceFile:6)
07-29 10:51:41.483 E/Xposed  (14561): 	at uos.a(SourceFile:53)
07-29 10:51:41.483 E/Xposed  (14561): 	at uos.b(SourceFile:36)
07-29 10:51:41.483 E/Xposed  (14561): 	at uos.c(SourceFile:39)
07-29 10:51:41.483 E/Xposed  (14561): 	at eti.a(SourceFile:11)
07-29 10:51:41.483 E/Xposed  (14561): 	at coo.run(SourceFile:5)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-29 10:51:41.483 E/Xposed  (14561): 	at ohq.run(SourceFile:24)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.lang.Thread.run(Thread.java:761)
07-29 10:51:41.483 E/Xposed  (14561): Caused by: android.database.sqlite.SQLiteException: no such table: ads (code 1): , while compiling: ALTER TABLE ads ADD COLUMN ad_intro_video_id TEXT
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
07-29 10:51:41.483 E/Xposed  (14561): 	at utp.a(SourceFile:2)
07-29 10:51:41.483 E/Xposed  (14561): 	at oix.onCreate(SourceFile:8)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
07-29 10:51:41.483 E/Xposed  (14561): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
07-29 10:51:41.483 E/Xposed  (14561): 	at ush.getWritableDatabase(SourceFile:22)
07-29 10:51:41.483 E/Xposed  (14561): 	at java.lang.reflect.Method.invoke(Native Method)
07-29 10:51:41.483 E/Xposed  (14561): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1217)
07-29 10:51:41.483 E/Xposed  (14561): 	... 22 more

And as a result - the module does not work :-(
YT 12.23.60
YTAA 3.5.3
A 7.1.2
Xposed 3.0.1

**Comment by rambomhtri** [comment] 2017-07-29 11:03
YouTube 12.27.53
Android 6.0.1
Xposed 3.1.1
AdAway 3.5.3

Everything is working just fine.

**Comment by rash230691** [comment] 2017-07-29 11:12
Can the problem in the android version? But on xda it is written that adaway works on 7.x.x

**Comment by wanam** [comment] 2017-07-29 11:34
@rash230691 Does your xposed version supports resources hooking?

Upload your xposed logs.

**Comment by rash230691** [comment] 2017-07-29 11:38
@wanam How can this be verified?
https://pastebin.com/Ny2iHegP

**Comment by punzilla** [comment] 2017-07-30 12:21
Hi ads have returned since recent updates. Please refer to my logs. In the most recent log I disabled all other modules except YouTube adaway and then restarted.

-----------------
30/07/2017 4:51:55 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'JDQ39.B9150XXUBMJ3' with fingerprint 'samsung/spcwifixx/spcwifi:4.2.2/JDQ39/B9150XXUBMJ3:user/release-keys'
Loading modules from /data/app/de.robv.android.xposed.mods.playstorefix-1.apk
  Loading class de.robv.android.xposed.mods.playstorefix.PlayStoreFix
Loading modules from /data/app/com.germainz.yourtube-1.apk
  Loading class com.germainz.yourtube.XposedMod
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
  Loading class ma.wanam.youtubeadaway.ResXposed
Loading modules from /data/app/com.pyler.nodevicecheck-1.apk
  Loading class com.pyler.nodevicecheck.NoDeviceCheck
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at com.germainz.yourtube.XposedMod.handleLoadPackage(XposedMod.java:59)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/google/android/apps/youtube/app/WatchWhileActivity
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.youtube.app.WatchWhileActivity" on path: /data/app/com.google.android.youtube-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 23 more
YouTube: com.google.android.youtube 12.27.53 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: Successfully hooked ads DB: use
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube AdAway: Successfully hooked qey param=ovb
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube: com.google.android.apps.youtube.kids 2.07.2 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: Successfully hooked ads DB: iab
-----------------
30/07/2017 11:21:49 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'JDQ39.B9150XXUBMJ3' with fingerprint 'samsung/spcwifixx/spcwifi:4.2.2/JDQ39/B9150XXUBMJ3:user/release-keys'
Loading modules from /data/app/de.robv.android.xposed.mods.playstorefix-1.apk
  Loading class de.robv.android.xposed.mods.playstorefix.PlayStoreFix
Loading modules from /data/app/com.germainz.yourtube-1.apk
  Loading class com.germainz.yourtube.XposedMod
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
  Loading class ma.wanam.youtubeadaway.ResXposed
Loading modules from /data/app/com.pyler.nodevicecheck-1.apk
  Loading class com.pyler.nodevicecheck.NoDeviceCheck
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at com.germainz.yourtube.XposedMod.handleLoadPackage(XposedMod.java:59)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.google.android.apps.youtube.app.WatchWhileActivity
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/google/android/apps/youtube/app/WatchWhileActivity
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.youtube.app.WatchWhileActivity" on path: /data/app/com.google.android.youtube-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 23 more
YouTube: com.google.android.youtube 12.27.53 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube AdAway: Successfully hooked ads DB: use
YouTube AdAway: Successfully hooked qey param=ovb
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: brute force failed! Class/Param sequence not found
-----------------
30/07/2017 12:04:43 PM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'JDQ39.B9150XXUBMJ3' with fingerprint 'samsung/spcwifixx/spcwifi:4.2.2/JDQ39/B9150XXUBMJ3:user/release-keys'
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
  Loading class ma.wanam.youtubeadaway.ResXposed
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube: com.google.android.youtube 12.27.53 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: Successfully hooked ads DB: use
YouTube AdAway: Successfully hooked qey param=ovb
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube AdAway 3.5.3: Trying brute force way...
YouTube AdAway: brute force failed! Class/Param sequence not found

**Comment by punzilla** [comment] 2017-07-30 12:24
My android version is 4.4.2 
I have 2 different versions of YouTube installed on this media centre -Samsung home sync.
I've attempted to update xposed modules, disable the others then restarted.

Hope this assists.

Thank you.

**Comment by wanam** [comment] 2017-09-20 07:52
Please test 3.6.1 update.

**Comment by punzilla** [comment] 2017-11-04 11:11
Hi  there ads are still showing up on my YouTube.
I'm still getting errors in the logs as follows. I'm running Android 4.2.2 an older version of YouTube for Google TV. Please let me know if you require further information. 

Thanks

-----------------
04/11/2017 11:04:32 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'JDQ39.B9150XXUBMJ3' with fingerprint 'samsung/spcwifixx/spcwifi:4.2.2/JDQ39/B9150XXUBMJ3:user/release-keys'
Loading modules from /data/app/ma.wanam.youtubeadaway-1.apk
  Loading class ma.wanam.youtubeadaway.Xposed
  Loading class ma.wanam.youtubeadaway.ResXposed
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube: com.google.android.youtube 12.42.59 loaded!
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube AdAway: Successfully hooked ads wrapper 
YouTube AdAway: Successfully hooked ads fetchers
YouTube: com.google.android.youtube.googletv 1.3.10 loaded!
YouTube: com.google.android.youtube 12.42.59 loaded!
YouTube AdAway: Successfully hooked ads DB ygv
YouTube AdAway: Successfully hooked ads wrapper 
YouTube AdAway: brute force failed! Class/Param sequence not found
YouTube AdAway: Successfully hooked ads fetchers

**Comment by wanam** [comment] 2017-11-09 15:52
Please update the module and try against the latest YouTube version, then post your xposed logs if the issue persists.

**Comment by wanam** [comment] 2018-02-06 15:00
Fixed on 4.1.0.

**Closed by wanam** 2018-02-06 15:00 UTC
