### ISSUE TITLE
Ads on the last few version of Youtube and the module.

### ISSUE THREAD

**Issue by gro0** [wanam/YouTubeAdAway#32] opened 2017-11-09 17:52 UTC
![screenshot_20171109-231328](https://user-images.githubusercontent.com/28336408/32620999-bea22346-c5a4-11e7-8cb1-3f6ca089a492.jpg)
[xposed_error_20171109_231528.log](https://github.com/wanam/YouTubeAdAway/files/1458657/xposed_error_20171109_231528.log)

Hi
Been getting ads at the start of videos for a couple of days now. 

Updated the module today, but ads persisted. There are no ad banner at the top of the home page, but there are ads when the video starts, and a banner at the bottom.

I disabled the only other module I had, minminguard, and rebooted, then cleared youtube data.

I have attached logs and a screenshot. Was not seeing ads after the reboot, but after maybe 2-3 mins, they came back.

I went through the logs, but there weren't any errors that I can tell. Stumped here.

**Comment by gro0** [comment] 2017-11-09 17:55
Oh, I uploaded a screenshot, but I dont think I got attached properly.
![screenshot_20171109-231328](https://user-images.githubusercontent.com/28336408/32621237-237a7ec6-c5a5-11e7-8817-12f256950f9e.jpg)

**Comment by ezaechiel** [comment] 2017-11-10 09:22
Same issue for me on One plus 5, Android 7.1.1, with last YouTube version 12.43.52.
I tried to uninstall xposed framework, install it again with all updated version from official repository of rovo89 but still the same issue.
No error in the log, the install has been correctly processed. And the module is activated, phone rebooted.

**Comment by ezaechiel** [comment] 2017-11-10 09:24
Here is the log :

11-10 09:06:09.911 I/Xposed  (  846): -----------------
11-10 09:06:09.911 I/Xposed  (  846): Starting Xposed version 88.2, compiled for SDK 25
11-10 09:06:09.911 I/Xposed  (  846): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
11-10 09:06:09.911 I/Xposed  (  846): ROM: ONEPLUS A5000_23_171031
11-10 09:06:09.911 I/Xposed  (  846): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/10171617:user/release-keys
11-10 09:06:09.911 I/Xposed  (  846): Platform: arm64-v8a, 64-bit binary, system server: yes
11-10 09:06:09.911 I/Xposed  (  846): SELinux enabled: yes, enforcing: yes
11-10 09:06:10.920 I/Xposed  (  846): -----------------
11-10 09:06:10.920 I/Xposed  (  846): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-10 09:06:11.590 I/Xposed  (  846): Detected ART runtime
11-10 09:06:11.599 I/Xposed  (  846): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-10 09:06:11.850 I/Xposed  (  846): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
11-10 09:06:11.865 I/Xposed  (  846):   Loading class ma.wanam.youtubeadaway.Xposed
11-10 09:06:11.866 I/Xposed  (  846):   Loading class ma.wanam.youtubeadaway.ResXposed
11-10 09:06:19.823 I/Xposed  (  847): -----------------
11-10 09:06:19.823 I/Xposed  (  847): Starting Xposed version 88.2, compiled for SDK 25
11-10 09:06:19.823 I/Xposed  (  847): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
11-10 09:06:19.823 I/Xposed  (  847): ROM: ONEPLUS A5000_23_171031
11-10 09:06:19.823 I/Xposed  (  847): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/10171617:user/release-keys
11-10 09:06:19.823 I/Xposed  (  847): Platform: arm64-v8a, 32-bit binary, system server: no
11-10 09:06:19.823 I/Xposed  (  847): SELinux enabled: yes, enforcing: yes
11-10 09:06:19.825 I/Xposed  (  847): -----------------
11-10 09:06:19.825 I/Xposed  (  847): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-10 09:06:20.220 I/Xposed  (  847): Detected ART runtime
11-10 09:06:20.229 I/Xposed  (  847): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-10 09:06:20.397 I/Xposed  (  847): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
11-10 09:06:20.529 I/Xposed  (  847):   Loading class ma.wanam.youtubeadaway.Xposed
11-10 09:06:20.529 I/Xposed  (  847):   Loading class ma.wanam.youtubeadaway.ResXposed
11-10 09:07:10.621 I/Xposed  ( 5788): YouTube: com.google.android.youtube 12.43.52 loaded!
11-10 09:07:11.838 I/Xposed  ( 5788): YouTube AdAway: Successfully hooked ads DB yka
11-10 09:07:13.072 I/Xposed  ( 5788): YouTube AdAway: Successfully hooked ads wrapper 
11-10 09:07:16.406 I/Xposed  ( 5788): YouTube AdAway: Successfully hooked ads fetchers
11-10 09:14:44.570 I/Xposed  ( 9466): YouTube: com.google.android.youtube 12.43.52 loaded!
11-10 09:14:45.122 I/Xposed  ( 9466): YouTube AdAway: Successfully hooked ads DB yka
11-10 09:14:45.664 I/Xposed  ( 9466): YouTube AdAway: Successfully hooked ads wrapper 
11-10 09:14:46.734 I/Xposed  ( 9466): YouTube AdAway: Successfully hooked ads fetchers
11-10 10:12:57.050 I/Xposed  (14680): YouTube: com.google.android.youtube 12.43.52 loaded!
11-10 10:12:57.727 I/Xposed  (14680): YouTube AdAway: Successfully hooked ads DB yka
11-10 10:12:58.311 I/Xposed  (14680): YouTube AdAway: Successfully hooked ads wrapper 
11-10 10:12:59.409 I/Xposed  (14680): YouTube AdAway: Successfully hooked ads fetchers

**Comment by wanam** [comment] 2017-11-10 09:51
@gro0 at least you should not get the ad banner on the bottom of the video, this may be caused by minminguard, take a look [here](https://github.com/wanam/YouTubeAdAway/issues/33#issuecomment-343411609).
@ezaechiel Unfortunately i cannot reproduce any ads with the same config (OP5 + stock 7.1.1 + xposed 88.2), region dependent ads maybe, but i cannot track them if i can't get them to show up.

**Comment by ezaechiel** [comment] 2017-11-10 10:07
Yes I clearly understand, maybe in another version it will work again, the previous one worked perfectly before the updates :).

For information my region is France if it could helps.

Thanks a lot for your answer and your great job :). I installed xposed framework only for your module :).

**Comment by gro0** [comment] 2017-11-10 18:39
I have minminguard disabled, I cleared youtube data, and cleared dalvik/cache.

I'll try removing minminguard, and wiping caches to see if anything improves and report back.

**Comment by gro0** [comment] 2017-11-10 19:44
![Uploading Screenshot_20171111-005959.jpg…]()
[Uploading xposed_error_20171111_010035.log…]()
Removed minminguard, cleared youtube cache and data, rebooted to recovery and deleted dalvik/cache.

Ads are displayed. 

Would a dirty flash help, or perhaps downgrading to an older version of youtube?

**Comment by gro0** [comment] 2017-11-10 19:52
[xposed_error_20171111_010035.log](https://github.com/wanam/YouTubeAdAway/files/1462549/xposed_error_20171111_010035.log)
![screenshot_20171111-005959](https://user-images.githubusercontent.com/28336408/32675883-84fe9022-c67e-11e7-8043-cf7a763bda9b.jpg)

The attachments weren't uploading properly I guess.

**Comment by lobezno223** [comment] 2017-11-11 15:14
Hello,

YT ads are displayed under latest YT app update 12.44.52. My region is Spain and here are my device specs:

OS - Kitkat 4.4.2
Display - 320dpi
CPU Arch. - ARMv7 Processor rev3 (v7l)
armeabi-v7a (Kernel armv7l)

**Comment by r2987554** [comment] 2017-11-12 00:37
A couple days ago, video ads suddenly began to appear on YT 12.15.x, so I updated both the app and module. Tried newer versions, focusing on those mentioned in "Tested against", with no success. Now I have clean Lineage (7.1.2), new Xposed 88.2 and 3.7.0 module. Same result as with the old config: video ads appear randomly at the video start, more frequently in autoplay or playlist. Sometimes a channel icon in bottom right corner and the small "i" hint in top right are displayed during playback as well.

Galaxy Tab S 8.4 (klimtwifi)
CM12.1 [old]; Lineage 14.1 [new]
Framework 87 (?) [old;] 88.2 [new]
Module 3.5.3 [old]; 3.7.0 [new]
YT: 12.43.52 [on older config, tested different stable versions from 12.15.x up]
Ads region: Poland
No Google account present
A couple days ago, video ads suddenly began to appear on YT 12.15.x, so I updated both the app and module. Tried newer versions, focusing on those mentioned in "Tested against", with no success. Now I have clean Lineage (7.1.2), new Xposed 88.2 and 3.7.0 module. Same result as with the old config: video ads appear randomly at the video start, more frequently in autoplay or playlist. Sometimes a channel icon in bottom right corner and the small "i" hint in top right are displayed during playback as well.

Galaxy Tab S 8.4 (klimtwifi)
CM12.1 [old]; Lineage 14.1 [new]
Framework 87 (?) [old;] 88.2 [new]
Module 3.5.3 [old]; 3.7.0 [new]
YT: 12.43.52 [on older config, tested different stable versions from 12.15.x up]
Ads region: Poland
No Google account present

**Comment by telxonius** [comment] 2017-11-14 04:03
I'm getting this too, same exact issues on my Samsung Note 3 (tmobile version) running 5.0
[https://flic.kr/p/21vPCTi](url)

**Comment by theArhar** [comment] 2017-11-16 18:14
I have commented on other topic, but yes, ads here
[xposed_error_20171116_210905.log](https://github.com/wanam/YouTubeAdAway/files/1479684/xposed_error_20171116_210905.log)

**Comment by theArhar** [comment] 2017-11-16 18:26
also suggestions (i) very annoying

**Comment by ngosang** [comment] 2017-11-18 17:28
@wanam I found the problem, I can reproduce.
1) **With this configuration it's working without ads**
Android 7.0.0
Xposed 88.2
Youtube 12.44.53 (last version in GPlay)
Youtube AdAway 3.7.0
2) **If I install MinMinGuard 2.0.beta5 I see the ads again, even if Youtube AdAway is enabled.**

By now I have MinMinGuard disabled but I try to fix it please :)

**Comment by trumad** [comment] 2017-11-19 20:49
I don't use MinMinGuard and I still have ads in youtube using youtube adaway.

**Comment by YaPaY** [comment] 2017-11-22 19:21
Same here, no minminGuard but still have ads

**Comment by adelino660** [comment] 2017-12-16 16:44
Hi i got it working with an older version of youtube adaway 3.5.1 and using youtube version 12.05.53

This should fix the problem, just don't update youtube nor use a newer version of youtube adaway.

I never updated the app for my tablet with this setup, and i was having the same issues once i updated to the latest youtube version along with the youtube adaway module. ( on my phone) I reverted back to the older versions on my phone and the adblocking is back in business.

Reposting - hope this helps anyone

**Comment by gro0** [comment] 2017-12-16 17:16
This does help a lot, I'll try it tonight. Thanks. 

⁣Sent from BlueMail ​

**Comment by ngosang** [comment] 2018-01-07 20:34
I compiled YoutubeAdAway 3.8.0 form source. Please test the APK and share your results.
Download => https://github.com/wanam/YouTubeAdAway/issues/41#issuecomment-355850303

**Comment by wanam** [comment] 2018-02-06 15:01
Fixed on 4.1.0.

**Closed by wanam** 2018-02-06 15:01 UTC
