### ISSUE TITLE
No blocking ads anymore

### ISSUE THREAD

**Issue by rophiroth** [wanam/YouTubeAdAway#127] opened 2023-01-20 11:24 UTC
All ads are back on latest version 17.49.34, background play still working

**Comment by wanam** [comment] 2023-01-20 16:47
I cannot reproduce your issue, the last update 5.0.4 was testing and working fine with YouTube versions up to 18.02.34.

Try with the latest update 5.0.4 and please provide your Xposed logs if the issue presists?

**Comment by wanam** [comment] 2023-02-11 17:43
Closing this one as there are no updates or logs provided.

**Closed by wanam** 2023-02-11 17:43 UTC
