### ISSUE TITLE
youtube minimizes when clicked back button while watching videos

### ISSUE THREAD

**Issue by gengooro** [wanam/YouTubeAdAway#159] opened 2023-08-25 08:45 UTC
When click back button while playing videos on YouTube, instead of minimising the video the whole youtube app minimizes..

thought that youtube has bug, but when disabled the YoutubeAdAway, everything works fine, so the bug is in the YoutubeAdAway..

**Comment by wanam** [comment] 2023-09-16 12:35
This is related to the hide cards feature which is an experimental patch (duplicate of https://github.com/wanam/YouTubeAdAway/issues/129).

**Closed by wanam** 2023-09-16 12:35 UTC
Labels: duplicate
